version: "2"
linters:
  default: all
  disable:
    - cyclop
    - noinlineerr
    - depguard
    - err113
    - exhaustruct
    - funlen
    - gocognit
    - gomoddirectives
    - gomodguard
    - intrange
    - ireturn
    - lll
    - maintidx
    - mnd
    - nlreturn
    - nonamedreturns
    - testpackage
    - wrapcheck
    - wsl
  settings:
    errcheck:
      check-type-assertions: true
    forbidigo:
      forbid:
        - pattern: ^fmt\.Print
        - pattern: ^log\.
        - pattern: ^print$
        - pattern: ^println$
        - pattern: ^panic$
    godox:
      keywords:
        - FIXME
    varnamelen:
      ignore-decls:
        - T any
        - i int
        - wg sync.WaitGroup
        - ok bool
        - w io.Writer
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
