# Copyright 2020-2026 Buf Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: invoice/v1/invoice_service.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'invoice/v1/invoice_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from invoice.v1 import invoice_pb2 as invoice_dot_v1_dot_invoice__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n invoice/v1/invoice_service.proto\x12\ninvoice.v1\x1a\x18invoice/v1/invoice.proto\"E\n\x14\x43reateInvoiceRequest\x12-\n\x07invoice\x18\x01 \x01(\x0b\x32\x13.invoice.v1.InvoiceR\x07invoice\"P\n\x15\x43reateInvoiceResponse\x12\x1d\n\ninvoice_id\x18\x01 \x01(\tR\tinvoiceId\x12\x18\n\x07version\x18\x02 \x01(\x04R\x07version2f\n\x0eInvoiceService\x12T\n\rCreateInvoice\x12 .invoice.v1.CreateInvoiceRequest\x1a!.invoice.v1.CreateInvoiceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'invoice.v1.invoice_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEINVOICEREQUEST']._serialized_start=74
  _globals['_CREATEINVOICEREQUEST']._serialized_end=143
  _globals['_CREATEINVOICERESPONSE']._serialized_start=145
  _globals['_CREATEINVOICERESPONSE']._serialized_end=225
  _globals['_INVOICESERVICE']._serialized_start=227
  _globals['_INVOICESERVICE']._serialized_end=329
# @@protoc_insertion_point(module_scope)
