# Copyright 2025 Buf Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: invoice/v1/invoice.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'invoice/v1/invoice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18invoice/v1/invoice.proto\x12\ninvoice.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x01\n\x07Invoice\x12\x1d\n\ninvoice_id\x18\x01 \x01(\tR\tinvoiceId\x12\x1d\n\naccount_id\x18\x02 \x01(\tR\taccountId\x12=\n\x0cinvoice_date\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0binvoiceDate\x12\x33\n\nline_items\x18\x04 \x03(\x0b\x32\x14.invoice.v1.LineItemR\tlineItems\"\x86\x01\n\x08LineItem\x12 \n\x0cline_item_id\x18\x01 \x01(\tR\nlineItemId\x12\x1d\n\nproduct_id\x18\x02 \x01(\tR\tproductId\x12\x1a\n\x08quantity\x18\x03 \x01(\x04R\x08quantity\x12\x1d\n\nunit_price\x18\x04 \x01(\x04R\tunitPriceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'invoice.v1.invoice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INVOICE']._serialized_start=74
  _globals['_INVOICE']._serialized_end=261
  _globals['_LINEITEM']._serialized_start=264
  _globals['_LINEITEM']._serialized_end=398
# @@protoc_insertion_point(module_scope)
