# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bufbuild/weather/v1/weather_service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'bufbuild/weather/v1/weather_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)bufbuild/weather/v1/weather_service.proto\x12\x13\x62ufbuild.weather.v1\x1a\x1b\x62uf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x02\n\x11GetWeatherRequest\x12+\n\x08latitude\x18\x01 \x01(\x02\x42\x0f\xbaH\x0c\n\n\x1d\x00\x00\xb4\x42-\x00\x00\xb4\xc2R\x08latitude\x12-\n\tlongitude\x18\x02 \x01(\x02\x42\x0f\xbaH\x0c\n\n\x1d\x00\x00\x34\x43-\x00\x00\x34\xc3R\tlongitude\x12\xc2\x01\n\rforecast_date\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x80\x01\xbaH}\xba\x01z\n\x1d\x66orecast_date.within_72_hours\x12+Forecast date must be in the next 72 hours.\x1a,this >= now && this <= now + duration(\'72h\')R\x0c\x66orecastDateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bufbuild.weather.v1.weather_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETWEATHERREQUEST'].fields_by_name['latitude']._loaded_options = None
  _globals['_GETWEATHERREQUEST'].fields_by_name['latitude']._serialized_options = b'\272H\014\n\n\035\000\000\264B-\000\000\264\302'
  _globals['_GETWEATHERREQUEST'].fields_by_name['longitude']._loaded_options = None
  _globals['_GETWEATHERREQUEST'].fields_by_name['longitude']._serialized_options = b'\272H\014\n\n\035\000\0004C-\000\0004\303'
  _globals['_GETWEATHERREQUEST'].fields_by_name['forecast_date']._loaded_options = None
  _globals['_GETWEATHERREQUEST'].fields_by_name['forecast_date']._serialized_options = b'\272H}\272\001z\n\035forecast_date.within_72_hours\022+Forecast date must be in the next 72 hours.\032,this >= now && this <= now + duration(\'72h\')'
  _globals['_GETWEATHERREQUEST']._serialized_start=129
  _globals['_GETWEATHERREQUEST']._serialized_end=437
# @@protoc_insertion_point(module_scope)
