package main

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + "_boilerplate.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	printHeader(g, file)

	for _, message := range file.Messages {
		printMessage(g, message)
	}
}

func printHeader(g *protogen.GeneratedFile, file *protogen.File) {
	g.P("// Code generated by protobuf-plugin-boilerplate. DO NOT EDIT THIS FILE.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
}

func printMessage(g *protogen.GeneratedFile, message *protogen.Message) {
	g.P(fmt.Sprintf("type %s struct {", message.Desc.Name()))

	for _, field := range message.Fields {
		printField(g, field)
	}

	g.P("}")
	g.P()
}

func printField(g *protogen.GeneratedFile, field *protogen.Field) {
	g.P(fmt.Sprintf("        %s %s `json:\"%s\"", field.GoName, field.Desc.Kind(), strings.ToLower(field.GoName)))
}
